name: Go_RestAPI
on:
  push:
    branches:
      - "main"
env:
  GO_VERSION: 1.17.6
jobs:
  # build workflow
  build:
    runs-on: ubuntu-latest
    steps:
    - name: set up go ${{env.GO_VERSION}}
      uses: actions/setup-go@v1
      with:
        go-version: ${{env.GO_VERSION}}
      id: go
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run build
      run: go build .
    - name: Run vet & lint
      run: |
        go vet .
        golint .
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build] # Only run this workflow when "build" workflow succeeds
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    # - name: Login to Github Packages
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GHCR_PAT }}

    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build image and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: .
        # Note: tags has to be all lower-case
        tags: |
          ghcr.io/randsw/go_restapi:${{ steps.vars.outputs.sha_short }}
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}

